name:                hsAutoscaling
version:             0.1.0.0
github:              "githubuser/hsAutoscaling"
license:             BSD3
author:              "Sebastian Pulido"
maintainer:          "example@example.com"
copyright:           "2023 Sebastian Pulido"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hsAutoscaling#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - amazonka
  - amazonka-ec2
  - bytestring
  - containers
  - deepseq
  - grpc-haskell
  - grpc-haskell
  - proto3-suite
  - proto3-wire
  - text
  - vector

executables:
  hsAutoscaling-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsAutoscaling

tests:
  hsAutoscaling-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsAutoscaling
