resolver: lts-18.28

packages:
- .

extra-deps:
- git: git@github.com:awakesecurity/gRPC-haskell.git
  commit: c6d91e58f2ef7a2a78016ba5590a7c90cf235740
  subdirs:
  - .
  - core
- amazonka-1.6.1
- amazonka-ec2-1.6.1
- proto3-suite-0.5.1
- proto3-wire-1.4.0
- unliftio-core-0.1.2.0
- word-compat-0.0.6
